version: "3"
services:
  worker:
      build:
      environment:
        ADMINS: $ADMINS
        API_HASH: $API_HASH 
        API_ID: $API_ID 
        BOT_TOKEN: $BOT_TOKEN 
        CHANNEL_ID: $CHANNEL_ID
        OWNER_ID: $OWNER_ID
        FORCE_SUB_CHANNEL: $FORCE_SUB_CHANNEL
        
