version: "3"
services:
  vote:
    build: vote
    scale: 2
    environment:
      - FLASK_ENV=development
    command: python app.py
    ports:
      - 8080:8080
        ADMINS: $ADMINS
        API_HASH: $API_HASH 
        API_ID: $API_ID 
        BOT_TOKEN: $BOT_TOKEN
        
