version: "3"
services:
  vote:
    build: vote
    scale: 2
    environment:
      - FLASK_ENV=development
    command: python app.py
    ports:
      - 8080:8080
    volumes:
      - ./vote:/src

  redis:
    image: redis
    ports:
      - 6379
    volumes:
      - redis:/data

volumes:
  redis:
services:
  worker:
      build:
      environment:
        ADMINS: $ADMINS
        API_HASH: $API_HASH 
        API_ID: $API_ID 
        BOT_TOKEN: $BOT_TOKEN
        
